Plugin1/Areas/Plugin1/ViewModels/MyViewModel.cs
namespace Plugin1.Areas.Plugin1.ViewModels
{
    public class MyViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

Plugin1/Areas/Plugin1/Components/MyViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Plugin1.Areas.Plugin1.ViewModels;

namespace Plugin1.Areas.Plugin1.Components
{
    public class MyViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var model = new MyViewModel
            {
                Id = 20,
                Name = "Awesome"
            };

            return View(model);
        }
    }
}

Plugin1/Areas/Plugin1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Plugin1.Areas.Plugin1.ViewModels;

namespace Plugin1.Areas.Plugin1.Controllers
{
    [Area("Plugin1")]
    public class HomeController : Controller
    {
        [HttpGet("/plugin1")]
        public IActionResult Index()
        {
            var model = new MyViewModel
            {
                Id = 10,
                Name = "Super coool"
            };

            return View(model);
        }

        [HttpGet("/plugin1/test")]
        public IActionResult Test()
        {
            return View();
        }
    }
}

Plugin1/Areas/Plugin1/Views/Home/Index.cshtml
@model Plugin1.Areas.Plugin1.ViewModels.MyViewModel

<h1>Plugin 1 --> Home --> Index</h1>

<h2>From view model: @Model.Name</h2>

Plugin1/Areas/Plugin1/Views/Home/Test.cshtml
<h1>Plugin 1 --> Home --> Test</h1>

@await Component.InvokeAsync("My")

Plugin1/Areas/Plugin1/Views/Shared/Components/My/Default.cshtml
@model Plugin1.Areas.Plugin1.ViewModels.MyViewModel

<h1>This is my view component</h1>
<h2>View model data: @Model.Name</h2>